src/ProfileBundle/Entity/Developer.php
<?php
namespace ProfileBundle\Entity;

use Doctrine\ORM\Mapping as ORM,
    Symfony\Component\Validator\Constraints as Assert;

/**
 * Developers
 *
 * @ORM\Table(name="developers")
 * @ORM\Entity(repositoryClass="ProfileBundle\Entity\DeveloperRepository")
 */
class Developer extends CustomUser
{
    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255,  unique=false, nullable=false)
     * @Assert\Length(min=3, max=255)
     * @Assert\NotBlank
     */
    protected $email;

    /**
     * @var string
     *
     * @ORM\Column(name="qualification", type="string", length=80, nullable=true)
     */
    private $qualification;

    /**
     * @var string
     *
     * @ORM\Column(name="level", type="string", length=10)
     */
    private $level;

    /**
	 * @var string
	 *
	 * @ORM\Column(name="main_skill", type="string", length=80, nullable=true)
	 */
    private $main_skill;

    /**
     * @var string
     *
     * @ORM\Column(name="skills", type="array")
     */
    private $skills = array();

    /**
     * @var string
     *
     * @ORM\Column(name="english", type="string", length=30)
     */
    private $english;

    /**
     * @var integer
     *
     * @ORM\Column(name="rate", type="smallint")
     */
    private $rate;

    /**
     * @var string
     *
     * @ORM\Column(name="location", type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=20, nullable=true)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="cv_uri", type="string", length=255, nullable=true)
     */
    private $cvUri;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @var integer
     *
     * @ORM\Column(name="count_show", type="integer", length=1)
     */
    private $countShow = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="active", type="integer")
     */
    private $active  = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="approved", type="integer")
     */
    private $approved  = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="rating", type="float")
     */
    protected $rating = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="sum_rating", type="float")
     */
    protected $sumRating = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="numVotes", type="smallint")
     */
    protected $numVotes = 0;

    /**
     * @var \DateTime
     * @ORM\Column(name="created_at", type="date")
     */
    protected $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="certificates", type="array")
     */
    private $certificates = array();

    public function __construct()
    {
        $this->createdAt = new \DateTime('now');
    }
    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getNumVotes()
    {
        return $this->numVotes;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @param mixed $numVotes
     */
    public function setNumVotes($numVotes)
    {
        $this->numVotes = $numVotes;
    }

    public function addVotes($vote)
    {
        $this->votes->add($vote);

        return $this;
    }

    public function removeVotes($vote)
    {
        $this->votes->remove($vote);

        return $this;
    }

    public function getVotes()
    {
        return $this->votes;
    }

    public function addFeedback($feedback)
    {
        $this->feedback->add($feedback);

        return $this;
    }

    public function removeFeedback($feedback)
    {
        $this->feedback->remove($feedback);

        return $this;
    }

    public function getFeedback()
    {
        return $this->feedback;
    }

    /**
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param float $rating
     */
    public function setRating($rating)
    {
        $this->rating = $rating;
    }

    /**
     * @return float
     */
    public function getSumRating()
    {
        return $this->sumRating;
    }

    /**
     * @param float $sumRating
     */
    public function setSumRating($sumRating)
    {
        $this->sumRating = $sumRating;
    }

    /**
     * @param  string     $qualification
     * @return Developers
     */
    public function setQualification($qualification)
    {
        $this->qualification = $qualification;

        return $this;
    }

    /**
     * @return string
     */
    public function getQualification()
    {
        return $this->qualification;
    }

    /**
     * Set level
     *
     * @param  string     $level
     * @return Developers
     */
    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * Get level
     *
     * @return string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Set skills
     *
     * @param  array      $skills
     * @return Developers
     */
    public function setSkills($skills)
    {
        $this->skills = $skills;

        return $this;
    }

    /**
     * Get skills
     *
     * @return array
     */
    public function getSkills()
    {
        return $this->skills;
    }

    /**
     * Set english
     *
     * @param  string     $english
     * @return Developers
     */
    public function setEnglish($english)
    {
        $this->english = $english;

        return $this;
    }

    /**
     * Get english
     *
     * @return string
     */
    public function getEnglish()
    {
        return $this->english;
    }

    /**
     * Set rate
     *
     * @param  integer    $rate
     * @return Developers
     */
    public function setRate($rate)
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * Get rate
     *
     * @return integer
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Set location
     *
     * @param  string     $location
     * @return Developers
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set type
     *
     * @param  string     $type
     * @return Developers
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param int $active
     */
    public function setActive($active)
    {
        $this->active = $active;
    }
    /**
     * @return int
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * @param int $approved
     */
    public function setApproved($approved)
    {
        $this->approved = $approved;

        return $this;
    }
    /**
     * @return int
     */
    public function getApproved()
    {
        return $this->approved;
    }

    /**
     * @param int $countShow
     */
    public function setCountShow($countShow)
    {
        $this->countShow = $countShow;

        return $this;
    }
    /**
     * @return int
     */
    public function getCountShow()
    {
        return $this->countShow;
    }

    /**
     * @param string $cvUri
     */
    public function setCvUri($cvUri)
    {
        $this->cvUri = $cvUri;

        return $this;
    }
    /**
     * @return string
     */
    public function getCvUri()
    {
        return $this->cvUri;
    }

    public function addEducations($educations)
    {
        $this->educations->add($educations);

        return $this;
    }

    public function removeEducations($educations)
    {
        $this->educations->remove($educations);

        return $this;
    }

    public function getEducations()
    {
        return $this->educations;
    }

    public function addEducation($educations)
    {
        $this->educations->add($educations);

        return $this;
    }

    public function removeEducation($educations)
    {
        $this->educations->remove($educations);

        return $this;
    }

    public function getEducation()
    {
        return $this->educations;
    }

    /**
     * @return string
     */
    public function getCertificates()
    {
        return $this->certificates;
    }

    /**
     * @param string $certificates
     */
    public function setCertificates($certificates)
    {
        $this->certificates = $certificates;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getMainSkill()
    {
        return $this->main_skill;
    }

    /**
     * @param string $main_skill
     */
    public function setMainSkill($main_skill)
    {
        $this->main_skill = $main_skill;
    }

}

src/ProfileBundle/Form/DeveloperType.php
<?php
namespace ProfileBundle\Form;

use Symfony\Component\Form\AbstractType,
    Symfony\Component\Form\FormBuilderInterface,
    Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DeveloperType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', null, array('label' => 'First Name', 'max_length' => 255, 'required' => false))
            ->add('lastname', null, array('label' => 'Last Name', 'max_length' => 255, 'required' => false))
            ->add('qualification', 'choice', array('label' => 'Speciality',
                'choices' => array('Frontend' => 'Frontend', 'Backend' => 'Backend', 'Full stack' => 'Full stack'),'attr'=> array('class'=>'qualif'), 'required' => false))
            ->add('level', 'choice', array('label' => 'Professional Level', 'max_length' => 255,
                    'choices' => array('Junior' => 'Junior', 'Middle' => 'Middle', 'Senior' => 'Senior')))
//			->add('main_skill', 'mainSkill', array('label' => 'Main Skill', 'required' => false, 'mapped' => true, 'attr' => array('placeholder' => 'Select your skills ...', 'class'=>'main_skill') ))
            ->add('skills', 'skills', array('label' => 'Professional Skills', 'required' => true, 'mapped' => true, 'attr' => array('placeholder' => 'Select your skills ...')))
//			->add('tags', 'tags', array('label' => 'Tags','required' => false))
            ->add('english', 'choice', array('label' => 'English Level', 'max_length' => 255,
                'choices' => array('Basic' => 'Basic', 'Intermediate' => 'Intermediate', 'Advanced' => 'Advanced')))
            ->add('rate', null, array('label' => 'Rate $/h', 'max_length' => 255, 'required' => false))
            ->add('description', 'textarea', array('label' => 'Profile Summary', 'required' => false))
            ->add('profileSummary', 'textarea', array('label' => 'Profile Summary', 'required' => false))
//            ->add('location', 'entity', array('max_length' => 255, 'class' => 'ArtelCustomerBundle:Cities', 'required' => false))
//			->add('country', 'choice', array('label' => 'Country', 'max_length' => 255, 'required' => false,
//				'choices'   => array('Ukraine' => 'Ukraine', 'Russia' => 'Russia', 'Belarus' => 'Belarus', 'Crimea' => 'Crimea'), 'data' => 'Ukraine'))
            //->add('company', null, array('label' => 'Company', 'max_length' => 255))
            ->add('description', 'textarea', array('label' => 'Comments', 'required' => false))
            ->add('skype', null, array('label' => 'Skype', 'max_length' => 255, 'required' => false))
            ->add('email', null, array('label' => 'Email', 'max_length' => 255, 'required' => false))
            ->add('telephone', null, array('label' => 'Telephone', 'max_length' => 255, 'required' => false))

            ->add('cvUri', null, array('label' => 'CV Upload', 'max_length' => 255))
            ->add('photo', 'text', array('required' => false, 'mapped' => false))
//            ->add('certificates', 'collection', array( 'label' => 'Certificates', 'type'   => 'text',))
//            ->add('workHistory','collection'
//                , array('type' =>  new WorkHistoryType(),'allow_add' => true,
//                                              'prototype' => true,
//                                              'by_reference' => false,))
//            ->add('educations','collection'
//                , array('type' =>  new EducationsType(),'allow_add' => true,
//                    'prototype' => true,
//                    'by_reference' => false,));
//            );
        ;

//        $builder->addEventSubscriber(new UploadFileSubscriber('cvUri', 'uploads/cv/'));
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ProfileBundle\Entity\Developer'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'developer';
    }
}

src/ProfileBundle/Form/Fields/CityType.php
<?php
namespace ProfileBundle\Form\Fields;

use Symfony\Component\Form\AbstractType,
    Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityManager;

class CityType extends AbstractType
{
    private $em;

    public function setEntityManager(EntityManager $em)
    {
        $this->em = $em;
    }

    public function getCity()
    {
        $citiess = $this->em->getRepository('PillsBundle:Cities')->findAll();
        $new_cities = array();

        foreach($citiess as $citie) {
            $new_cities[$citie->getCity()] = $citie->getCity();
        }

        asort($new_cities);

        return $new_cities;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => $this->getCity(),
            'multiple' => false,
            'required' => false,
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'cities';
    }
}

src/ProfileBundle/Resources/views/Developer/all_cv.html.twig
{{ form_errors(AllCv) }}
{{ form_start(AllCv, {'action': path('allcv', {'slug': developer.slug}), 'method': 'POST'}) }}

<div class="form-group">

    {{ form_label(AllCv.photo) }}
    {{ form_widget(AllCv.photo) }}

</div>

<div class="margin-top-20">
    {{ form_widget(AllCv.save, {'attr': {'class': 'btn green-haze'}}) }}
</div>

{{ form_end(AllCv) }}

src/ProfileBundle/Resources/views/Developer/form.html.twig
{% extends "ProfileBundle::layout.html.twig" %}

{% block container %}
    {{ form(form) }}
{% endblock %}

src/ProfileBundle/Resources/views/Developer/form_personal_information.html.twig
{#{% include "ArtelProfileBundle:Developer:profile_sidebar.html.twig" %}#}

{{ form_errors(infoForm) }}
{{ form_start(infoForm, {'action': path('profile_submit_personal_information', {'slug': developer.slug}), 'method': 'POST'}) }}

<div class="form-group">
    {{ form_label(infoForm.firstname, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.firstname, {'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_label(infoForm.lastname, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.lastname, {'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_label(infoForm.email, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.email, {'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_label(infoForm.country, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.country, {'attr': {'class': 'form-control select2 select2_sample4'}}) }}
</div>

<div class="form-group">
    {{ form_label(infoForm.city, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.city, {'attr': {'class': 'form-control select2 select2_sample4'}}) }}
</div>

<div class="form-group">
    {{ form_label(infoForm.skype, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.skype, {'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_label(infoForm.telephone, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(infoForm.telephone, {'attr': {'class': 'form-control mask_phone'}}) }}
</div>
<div class="margin-top-20">
    {{ form_widget(infoForm.save, {'attr': {'class': 'btn green-haze'}}) }}
</div>

{{ form_end(infoForm) }}

src/ProfileBundle/Resources/views/Developer/form_professional_skills.html.twig
{{ form_errors(skillsForm) }}
{{ form_start(skillsForm, {'action': path('profile_submit_professional_skills', {'slug': developer.slug}), 'method': 'POST'}) }}

<div class="form-group">
    {{ form_label(skillsForm.level, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(skillsForm.level, {'attr': {'class': 'form-control bs-select'}}) }}
</div>
<div class="form-group">
    {{ form_widget(skillsForm.qualification, {'attr': {'class': 'form-control bs-select'}}) }}
</div>
<div class="form-group">
    {{ form_widget(skillsForm.main_skill, {'attr': {'class': 'form-control input-xlarge select2me'}}) }}
</div>
<div class="form-group">
    {{ form_label(skillsForm.level, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(skillsForm.skills, {'attr': {'class': 'form-control chosen-select input-xlarge'}}) }}
</div>
<div class="form-group">
    {{ form_label(skillsForm.english, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(skillsForm.english, {'attr': {'class': 'form-control bs-select'}}) }}
</div>
<div class="form-group">
    {{ form_label(skillsForm.rate, label|default(null), {'label_attr': {'class': 'control-label'}}) }}
    <div class="input-medium">
        {{ form_widget(skillsForm.rate, {'attr': {'class': 'form-control touchspin_demo1'}}) }}
    </div>
</div>
<div class="margin-top-20">
    {{ form_widget(skillsForm.save, {'attr': {'class': 'btn green-haze'}}) }}
</div>

{{ form_end(skillsForm) }}

src/ProfileBundle/Resources/views/Developer/profile_header.html.twig
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">Profile</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{ path('get_all_posts') }}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <!--<li>-->
        <!--<a href="#">Pages</a>-->
        <!--<i class="fa fa-angle-right"></i>-->
        <!--</li>-->
        <li>
            <a href="{{ path('profile_homepage', {'slug': developer.slug}) }}">User Account</a>
        </li>
    </ul>
    <!--<div class="page-toolbar">-->
    <!--<div class="btn-group pull-right">-->
    <!--<button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">-->
    <!--Actions <i class="fa fa-angle-down"></i>-->
    <!--</button>-->
    <!--<ul class="dropdown-menu pull-right" role="menu">-->
    <!--<li>-->
    <!--<a href="#">Action</a>-->
    <!--</li>-->
    <!--<li>-->
    <!--<a href="#">Another action</a>-->
    <!--</li>-->
    <!--<li>-->
    <!--<a href="#">Something else here</a>-->
    <!--</li>-->
    <!--<li class="divider">-->
    <!--</li>-->
    <!--<li>-->
    <!--<a href="#">Separated link</a>-->
    <!--</li>-->
    <!--</ul>-->
    <!--</div>-->
    <!--</div>-->
</div>
<!-- END PAGE HEADER-->

src/ProfileBundle/Resources/views/Developer/profile_sidebar.html.twig
<!-- BEGIN PROFILE SIDEBAR -->
<div class="profile-sidebar">
    <!-- PORTLET MAIN -->
    <div class="portlet light profile-sidebar-portlet">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
            <img src="{{ developer.avatar }}" class="img-responsive" alt="">
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">
               {{ developer.firstname }} {{ developer.lastname }}
            </div>
            <div class="profile-usertitle-job">
                User
            </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->

        <!-- PHOTO UPLOAD START -->
        <div class="photoLoader">
            <form id="avatarForm" action={{ path("profile_photo_upload", {'slug': developer.slug}) }} method="post" enctype="multipart/form-data">
                <label>
                    <input id="Avatar" type="file" name="file"/>
                    <input type="submit" name="submitBtn" class="sbtn" value="Upload" />
                </label>
            </form>
        </div>
        <!-- PHOTO UPLOAD END -->

        <!-- STAT -->
        <div class="row list-separated profile-stat">
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="uppercase profile-stat-title">
                    {{ developer.rate }}
                </div>
                <div class="uppercase profile-stat-text">
                    Rate
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="uppercase profile-stat-title">
                    51
                </div>
                <div class="uppercase profile-stat-text">
                    Rating
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="uppercase profile-stat-title">
                    61
                </div>
                <div class="uppercase profile-stat-text">
                    XP
                </div>
            </div>
        </div>
        <!-- END STAT -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
            <ul class="nav">
                <li class="active">
                    <a href="#extra_profile_account.html">
                        <i class="icon-settings"></i>
                        Account Settings </a>
                </li>
                <li>
                    <a href="#extra_profile.html">
                        <i class="icon-check"></i>
                        Fitted Projects </a>
                </li>
                <li>
                    <a href="#page_todo.html" target="_blank">
                        <i class="icon-check"></i>
                        Project List </a>
                </li>
                <li>
                    <a href="#extra_profile_help.html">
                        <i class="icon-info"></i>
                        Blog </a>
                </li>
            </ul>
        </div>
        <!-- END MENU -->
    </div>
    <!-- END PORTLET MAIN -->
    <!-- PORTLET MAIN -->
    <!--<div class="portlet light">-->
    <!--<div>-->
    <!--<h4 class="profile-desc-title">About Marcus Doe</h4>-->
    <!--<span class="profile-desc-text"> Lorem ipsum dolor sit amet diam nonummy nibh dolore. </span>-->
    <!--<div class="margin-top-20 profile-desc-link">-->
    <!--<i class="fa fa-globe"></i>-->
    <!--<a href="http://www.keenthemes.com">www.keenthemes.com</a>-->
    <!--</div>-->
    <!--<div class="margin-top-20 profile-desc-link">-->
    <!--<i class="fa fa-twitter"></i>-->
    <!--<a href="http://www.twitter.com/keenthemes/">@keenthemes</a>-->
    <!--</div>-->
    <!--<div class="margin-top-20 profile-desc-link">-->
    <!--<i class="fa fa-facebook"></i>-->
    <!--<a href="http://www.facebook.com/keenthemes/">keenthemes</a>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!-- END PORTLET MAIN -->
</div>
<!-- END BEGIN PROFILE SIDEBAR -->